# Generated by Django 5.0 on 2023-12-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('generarPago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpago',
            name='cedula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientes'),
        ),
    ]
