# Generated by Django 5.0 on 2024-01-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generarPago', '0002_generarpago_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpago',
            name='cantidad_pagada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
