# Generated by Django 4.2.4 on 2024-01-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generarPago', '0002_generarpago_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpago',
            name='cantidad_pagada',
            field=models.DecimalField(decimal_places=4, default=1234, max_digits=10),
            preserve_default=False,
        ),
    ]
