# Generated by Django 5.0 on 2024-01-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generarPago', '0004_alter_generarpago_cantidad_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generarpago',
            name='cantidad_pagada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
