# Generated by Django 5.0 on 2023-12-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pagosMensuales',
            fields=[
                ('pagos_mensuales', models.AutoField(primary_key=True, serialize=False)),
                ('vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('opcion1', 'Cancelado'), ('opcion2', 'Por pagar')], default='opcion2', max_length=20)),
                ('total_cobrar', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Pagos_mensuales',
            },
        ),
    ]
