# Generated by Django 5.0 on 2023-12-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('meses_diferidos', models.CharField(choices=[('opcion1', '8 meses'), ('opcion2', '12 meses'), ('opcion3', '24 meses'), ('opcion4', '32 meses')], default='opcion1', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Planes',
            },
        ),
    ]
