# Generated by Django 5.0 on 2023-12-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='meses_diferidos',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
