# Generated by Django 4.2.4 on 2023-12-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_meses_diferidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='meses_diferidos',
        ),
    ]
