# Generated by Django 5.0 on 2023-12-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_alter_planes_meses_diferidos'),
        ('productos', '0003_remove_productos_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='meses_diferidos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planes.planes'),
        ),
    ]
