# Generated by Django 5.0 on 2023-12-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
    ]
