# Generated by Django 5.0 on 2023-12-21 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_nombre_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
