# Generated by Django 5.0 on 2023-12-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
