# Generated by Django 5.0 on 2023-12-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_clientes_nombre_producto'),
        ('crearPagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='total_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crearPagos.crear_pagos'),
        ),
    ]
