# Generated by Django 5.0 on 2023-12-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_clientes_total_pagar'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='meses_diferidos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planes.planes'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
