# Generated by Django 5.0 on 2023-12-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_clientes_meses_diferidos_alter_clientes_fecha_inicio'),
        ('pagosMensuales', '0002_pagosmensuales_user_pagosmensuales_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cantidad_producto',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='pagos_mensuales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagosMensuales.pagosmensuales'),
        ),
    ]
