# Generated by Django 5.0 on 2023-12-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_clientes_cantidad_producto_clientes_pagos_mensuales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='pagos_mensuales',
        ),
    ]
