# Generated by Django 5.0 on 2023-12-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_remove_clientes_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
